# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7580-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/universal7580-common

PRODUCT_COPY_FILES += \
    vendor/samsung/universal7580-common/proprietary/vendor/bin/gps.cer:$(TARGET_COPY_OUT_VENDOR)/bin/gps.cer

PRODUCT_PACKAGES += \
    libhwjpeg \
    libsensorlistener \
    libuniplugin \
    libGLES_mali \
    gps.universal7580 \
    libfloatingfeature \
    libprotobuf-cpp-fl26 \
    libsecnativefeature \
    libwvdrmengine \
    gpsd
